import { CTA, PageHero } from "@/components/Sections";
import { asset } from "@/lib/content";
import { createPageMetadata } from "@/lib/seo";

export const metadata = createPageMetadata({ title: "Náš tím a odborné zázemie", description: "Spoznajte zakladateľa Radovana Foltinského a odbornú konzultantku Dr. med. univ. Alexandru Foltinskú z REVIQA Biomedica.", path: "/nas-tim" });

export default function TeamPage() {
  return <><PageHero eyebrow="Náš tím" title="Odbornosť s ľudskou tvárou" text="Osobný prístup, dôkladné porozumenie a odborná konzultácia tvoria základ každej spolupráce." />
    <section className="section shell team-grid"><article className="person-card featured"><div className="portrait-crop"><img src={asset("/assets/radovan-foltinsky-portrait-2026.jpeg")} alt="Radovan Foltinský, zakladateľ REVIQA Biomedica" /></div><div><h2 className="person-name">Radovan Foltinský</h2><p className="person-titles">MSc, MEd, CertMGMT (Open)</p><p className="person-role">Zakladateľ &amp; Akreditovaný špecialista | REVIQA Biomedica</p><p>Aktívne pôsobil ako vrcholový manažér (CEO) v úspešných technologických spoločnostiach a člen správnej rady AVS. Ako univerzitný lektor viedol doktorandov a podieľal sa na vývojových aj výskumných projektoch. Dnes svoje bohaté manažérske aj akademické skúsenosti spája v misii pomáhať ľuďom pri návrate k plnej sile, zdraviu a životnej energii ako akreditovaný špecialista na neuromyoskeletálne systémy.</p><blockquote>„Mojím cieľom je priniesť nový štandard v privátnej regenerácii a dlhovekosti, kombinujúci vedu, skúsenosti a personalizovanú starostlivosť.<br /><br />Nezameriavame sa iba na miesto, ktoré bolí. Vnímame človeka ako celok.“</blockquote></div></article>
      <article className="person-card consultant"><div className="portrait-crop consultant-portrait"><img src={asset("/assets/alexandra-foltinska-portrait.jpg")} alt="Dr. med. univ. Alexandra Foltinská, Consulting Partner REVIQA Biomedica" /></div><div><h2 className="person-name">Alexandra Foltinská</h2><p className="person-titles">Dr. med. univ.</p><p className="person-role">Consulting Partner | REVIQA Biomedica</p><p>Lekárka registrovaná v Rakúskej lekárskej komore (ÖÄK) s aktívnou klinickou praxou v Tirolsku. Zastrešuje odborné lekárske konzultácie.</p><blockquote>„V REVIQA | BIOMEDICA sa snažíme spojiť modernú vedeckú medicínu s konceptom individuálnej regenerácie a prevencie.“</blockquote></div></article></section><CTA /></>;
}
