import Link from "next/link";
import { CTA, PageHero, SectionHeading } from "@/components/Sections";
import { asset } from "@/lib/content";
import { createPageMetadata } from "@/lib/seo";

export const metadata = createPageMetadata({ title: "O nás – filozofia a centrum", description: "Spoznajte filozofiu, odborné zázemie a pokojné prostredie súkromného regeneračného centra REVIQA Biomedica v Poprade.", path: "/o-nas" });

export default function AboutPage() {
  return <><PageHero eyebrow="O nás" title="Váš potenciál. Naša misia." text={<>Bolesť, únava a dlhodobé preťaženie nemusia byť vaším novým normálom. Potrebujete priestor, kde vás pozorne vypočujú, odborne zhodnotia váš stav a navrhnú riešenie na mieru.<br /><br />REVIQA Biomedica je privátne regeneračné &amp; longevity centrum v modernom modulovom pavilóne v rezidenčnom prostredí. Vytvorili sme útočisko pre všetkých, ktorí hľadajú špičkovú starostlivosť bez zbytočného zhonu.</>} image="/assets/center-garden-1.jpeg" />
    <section className="section shell why-reviqa"><div><SectionHeading eyebrow="Prečo REVIQA" title="Regenerácia začína porozumením." /><p>Veríme, že skutočná regenerácia nezačína terapiou, ale pochopením človeka. Preto sa nezameriavame iba na miesto, kde sa prejavujú ťažkosti. Hľadáme funkčné súvislosti, ktoré ovplyvňujú pohyb, nervový systém a celkovú rovnováhu organizmu.</p><span className="hero-divider" aria-hidden="true" /><h2>Individuálna starostlivosť</h2><h3>REVIQA Method™ | Chironeurogenic System™</h3><p>Naša autorská metodika spája biomechaniku, neuromyoskeletálnu manuálnu terapiu, fyzio-regeneračné postupy a moderné high-tech regeneračné technológie do jedného personalizovaného systému starostlivosti.</p><p>Nevyberáte si jednotlivé terapie. Na základe funkčného zhodnotenia vášho stavu spoločne vytvárame personalizovaný regeneračný protokol, ktorý rešpektuje vaše individuálne potreby, aktuálny funkčný stav a dlhodobé ciele.</p><p>Každý regeneračný protokol zostavujeme na mieru, pretože veríme, že skutočne individuálna starostlivosť je základom dlhodobých výsledkov.</p></div><div className="framed-image"><img src={asset("/assets/center-building-corrected.jpg")} alt="Moderný modulový pavilón centra REVIQA" /></div></section>
    <section className="section dark-panel"><div className="shell"><SectionHeading center eyebrow="Naše hodnoty" title="Ľudský prístup. Veda. Technológie." /><div className="values-grid"><article><span>01</span><h3>Individuálny prístup</h3><p>Rešpektujeme jedinečné potreby každého klienta.</p></article><article><span>02</span><h3>Diskrétnosť</h3><p>Dôvera a súkromie sú základom našej starostlivosti.</p></article><article><span>03</span><h3>Odbornosť</h3><p>Akreditovaní špecialisti sa rozhodujú na základe poznatkov, skúseností a precíznosti.</p></article><article><span>04</span><h3>Veda, technológie</h3><p>Využívame moderné high-tech technológie na podporu prirodzenej regenerácie organizmu.</p></article></div></div></section>
    <section className="section shell"><SectionHeading center eyebrow="Ľudia za REVIQA" title="Tím, ktorý vás počúva" /><div className="center-action"><Link className="gold-button" href="/nas-tim">Spoznať náš tím</Link></div></section><CTA /></>;
}
