export const contact = {
  phoneDisplay: "+421 917 072 074",
  phone: "+421917072074",
  email: "info@reviqa.sk",
  address: "Hitschova 5022/2, 058 01 Poprad – Spišská Sobota, Slovensko",
  whatsapp:
    "https://wa.me/421917072074?text=Dobr%C3%BD%20de%C5%88%2C%20m%C3%A1m%20z%C3%A1ujem%20o%20vstupn%C3%BA%20konzult%C3%A1ciu%20v%20REVIQA.",
};

export const services = [
  {
    slug: "hyperbaricka-oxygenoterapia",
    short: "HBOT",
    title: "Hyperbarická oxygenoterapia (HBOT)",
    eyebrow: "Podpora okysličenia",
    intro:
      "Vedecky používaný postup, pri ktorom klient dýcha kyslík v prostredí so zvýšeným tlakom. Cieľom je zvýšiť dostupnosť kyslíka pre tkanivá a podporiť regeneračný plán.",
    image: "/assets/service-hbot-concept.jpg",
    duration: "približne 60 minút",
    price: "od 50 €",
    process: [
      "Pred terapiou posúdime zdravotný stav, možné kontraindikácie a vhodnosť HBOT.",
      "Počas približne 60-minútového pobytu sa tlak v komore zvyšuje a následne kontrolovane znižuje.",
      "Klient pokojne odpočíva a komunikuje s obsluhou; protokol sa nastavuje individuálne.",
      "Po terapii sledujeme toleranciu a odporúčame ďalšiu frekvenciu podľa plánu.",
    ],
    benefits: ["zvýšená dostupnosť kyslíka", "podpora obnovy tkanív", "podpora hojivých procesov", "podpora vitality", "podpora mozgu a koncentrácie", "súčasť regenerácie po záťaži"],
    audience: "Pre klientov, pri ktorých vstupné odborné posúdenie potvrdí vhodnosť hyperbarickej oxygenoterapie.",
    suitableFor: ["chronická únava", "rekonvalescencia po úrazoch a výkonoch", "športovci a zvýšená fyzická záťaž", "kožné a hojivé ťažkosti", "znížená vitalita", "ďalšie stavy po odbornom odporúčaní"],
    modalities: ["individuálny HBOT protokol", "jedna terapia", "séria 5 terapií", "séria 10 terapií", "kombinácia s ďalšou starostlivosťou"],
    details: [
      ["Zvýšenie okysličenia", "HBOT zvyšuje dostupnosť kyslíka v krvi a tkanivách. Konkrétny účinok závisí od tlaku, dĺžky, nastaveného protokolu a zdravotného stavu klienta."],
      ["Obnova buniek a hojenie", "HBOT sa v regeneračných plánoch využíva na podporu prirodzených hojivých procesov, obnovy tkanív a zotavenia po vybraných typoch záťaže."],
      ["Zápal, bolesť a vitalita", "HBOT môže byť súčasťou individuálneho plánu pri podpore zvládania zápalovej záťaže, bolestivých stavov, imunity, energie a vitality. Vhodnosť vždy posudzujeme individuálne."],
      ["Mozog a nervový systém", "HBOT sa využíva aj pri podpore kognície, sústredenia a vybraných neuroprotektívnych mechanizmov. Nenahrádza neurologické vyšetrenie ani liečbu."],
    ],
    faq: [
      ["Čo budem počas terapie cítiť?", "Pri zmene tlaku môžete cítiť tlak v ušiach podobný letu lietadlom. Obsluha vysvetlí techniky vyrovnávania tlaku."],
      ["Koľko terapií potrebujem?", "Počet závisí od cieľa, zdravotného stavu a reakcie. V cenníku sú jedna terapia a balíky 5 alebo 10 terapií."],
      ["Je HBOT vhodná pre každého?", "Nie. Pred terapiou je potrebné individuálne posúdenie vrátane pľúcnych, ušných a ďalších zdravotných rizík."],
    ],
  },
  {
    slug: "molekularny-vodik",
    short: "H₂ terapia",
    title: "Molekulárna vodíková terapia (H₂)",
    eyebrow: "Regenerácia na bunkovej úrovni",
    intro:
      "Vodík je najmenšia molekula. V REVIQA ho zaraďujeme do personalizovaných plánov formou inhalácie alebo vodíkovej vody podľa individuálneho cieľa.",
    image: "/assets/service-hydrogen-concept.jpg",
    duration: "podľa individuálneho protokolu",
    price: "na základe plánu",
    process: [
      "Preberieme cieľ, zdravotný stav a miesto vodíkovej terapie v celom pláne.",
      "Vyberieme inhaláciu molekulárneho vodíka, pitie vodíkovej vody alebo ich vhodnú kombináciu.",
      "Nastavíme frekvenciu a dĺžku podľa individuálneho protokolu.",
      "Priebežne sledujeme toleranciu a upravujeme plán podľa potrieb klienta.",
    ],
    benefits: ["antioxidačná podpora", "podpora bunkovej rovnováhy", "podpora energie a vitality", "podpora mozgu a nervového systému", "podpora regenerácie", "začlenenie do longevity plánu"],
    audience: "Pre klientov, ktorí chcú podporiť regeneráciu, vitalitu a ochranu buniek v rámci individuálne posúdeného programu.",
    suitableFor: ["chronická únava", "športová a pracovná záťaž", "regenerácia po výkone", "zápalová záťaž", "podpora imunity", "anti-aging a longevity"],
    modalities: ["inhalácia molekulárneho vodíka", "pitie vodíkovej vody", "individuálny protokol", "kombinácia s HBOT", "dlhodobý regeneračný režim"],
    details: [
      ["Selektívna antioxidačná podpora", "Molekulárny vodík sa skúma pre svoje selektívne antioxidačné pôsobenie a schopnosť podporovať ochranu buniek pred oxidačným stresom."],
      ["Prenikanie na bunkovú úroveň", "Vďaka malej veľkosti molekuly môže vodík prenikať cez biologické membrány. Jeho využitie a spôsob podania vždy prispôsobujeme individuálnemu stavu a cieľu klienta."],
      ["Energia, vitalita a nervový systém", "Vodíková terapia môže podporovať činnosť mitochondrií, bunkovú energiu, vitalitu a celkovú mentálnu výkonnosť vrátane koncentrácie a spánku."],
      ["Regenerácia a longevity", "Vodík zaraďujeme ako doplnkový nástroj do širšieho plánu, nie ako náhradu diagnostiky alebo liečby ochorení."],
    ],
    faq: [
      ["Aký je rozdiel medzi inhaláciou a vodíkovou vodou?", "Inhalácia privádza vodík cez dýchacie cesty, vodíková voda cez tráviaci trakt. Výber závisí od cieľa a protokolu."],
      ["Môžem terapiu kombinovať s HBOT?", "Kombinácia je možná iba vtedy, keď ju odporučí individuálny plán a nie sú prítomné kontraindikácie."],
      ["Je vodík liekom?", "Na stránke ho prezentujeme ako doplnkový regeneračný postup. Nenahrádza lekársku diagnostiku, predpísanú liečbu ani lieky."],
    ],
  },
  {
    slug: "molekularny-kyslik",
    short: "O₂ terapia",
    title: "Molekulárna kyslíková terapia (O₂)",
    eyebrow: "Podpora okysličenia a regenerácie",
    intro:
      "Kyslíkovú terapiu zaraďujeme do personalizovaného regeneračného protokolu s cieľom podporiť okysličenie organizmu, bunkovú energiu a prirodzené regeneračné procesy.",
    image: "/assets/service-diagnostics-concept.jpg",
    duration: "podľa individuálneho protokolu",
    price: "na základe plánu",
    process: [
      "Pred terapiou zhodnotíme aktuálny zdravotný stav, potreby klienta a možné obmedzenia.",
      "Zvolíme vhodný spôsob podania a individuálne nastavenie kyslíkovej terapie.",
      "Počas aplikácie sledujeme komfort a toleranciu klienta.",
      "Terapia sa podľa potreby prepája s ďalšími modulmi REVIQA Method™.",
    ],
    benefits: ["podpora okysličenia organizmu", "podpora bunkovej energie", "podpora regenerácie po záťaži", "podpora vitality", "individuálne nastavenie", "súčasť personalizovaného protokolu"],
    audience: "Pre dospelých aj deti po individuálnom posúdení, pri ktorých je kyslíková terapia vhodnou súčasťou personalizovaného regeneračného protokolu.",
    suitableFor: ["znížená vitalita a únava", "regenerácia po fyzickej alebo psychickej záťaži", "podpora športovej regenerácie", "rekonvalescencia podľa odborného odporúčania", "podpora koncentrácie a výkonnosti", "individuálne regeneračné a longevity programy"],
    modalities: ["individuálne nastavený kyslíkový protokol", "inhalačná kyslíková podpora", "kombinácia s ďalšími modulmi REVIQA Method™", "séria podľa individuálneho plánu"],
    details: [
      ["Podpora dostupnosti kyslíka", "Kyslíková terapia môže podporiť dostupnosť kyslíka pre organizmus. Spôsob podania a intenzitu nastavujeme podľa zdravotného stavu a cieľa klienta."],
      ["Bunková energia a regenerácia", "Kyslík je nevyhnutný pre tvorbu bunkovej energie. V individuálnom protokole ho využívame ako podporu prirodzených regeneračných a adaptačných procesov."],
      ["Výkon a vitalita", "Terapia môže byť súčasťou programu zameraného na zvládanie záťaže, podporu vitality a návrat k bežným alebo športovým aktivitám."],
      ["Súčasť širšieho plánu", "Kyslíková terapia nenahrádza diagnostiku ani liečbu ochorení. Zaraďujeme ju iba po individuálnom posúdení ako jeden z modulov REVIQA Method™."],
    ],
    faq: [
      ["Ako sa kyslíková terapia nastavuje?", "Spôsob podania, intenzita a frekvencia vychádzajú z individuálneho zhodnotenia zdravotného stavu, cieľov a tolerancie klienta."],
      ["Je kyslíková terapia vhodná aj pre deti?", "Áno, iba po individuálnom posúdení a s nastavením primeraným veku a zdravotnému stavu. Dieťa prichádza so zákonným zástupcom."],
      ["Nahrádza kyslíková terapia liečbu?", "Nie. Ide o doplnkový regeneračný postup, ktorý nenahrádza lekársku diagnostiku, predpísanú liečbu ani lieky."],
    ],
  },
  {
    slug: "fotobiomodulacia",
    short: "Svetelná terapia",
    title: "Fotobiomodulácia (660–850 nm)",
    eyebrow: "Veda svetla. Energia života.",
    intro:
      "Fotobiomodulácia využíva vybrané vlnové dĺžky červeného a blízkeho infračerveného svetla na podporu prirodzených bunkových a regeneračných procesov.",
    image: "/assets/service-pbm-concept.jpg",
    duration: "podľa zvolenej oblasti a protokolu",
    price: "na základe plánu",
    process: [
      "Určíme cieľovú oblasť, cieľ terapie a vylúčime možné kontraindikácie.",
      "Nastavíme vlnovú dĺžku, vzdialenosť, intenzitu a čas expozície.",
      "Počas neinvazívnej aplikácie klient používa ochranu očí a pokojne odpočíva.",
      "Pri sérii stretnutí sledujeme reakciu a podľa potreby protokol upravujeme.",
    ],
    benefits: ["podpora bunkovej energie ATP", "podpora regulácie zápalovej záťaže", "podpora hojenia a obnovy tkanív", "podpora svalov a kĺbov", "podpora mozgu a nervov", "podpora vitality a longevity"],
    audience: "Pre dospelých aj deti, ak je svetelná terapia po odbornom posúdení vhodná a je možné bezpečne nastaviť protokol.",
    suitableFor: ["regenerácia kože a povrchových tkanív", "svaly, šľachy a kĺby", "zotavenie po záťaži", "podpora hojenia", "podpora výkonu", "longevity programy"],
    modalities: ["červené svetlo približne 660 nm", "blízke infračervené svetlo približne 810–850 nm", "lokálna aplikácia", "séria podľa individuálneho plánu"],
    details: [
      ["Ako svetlo pôsobí", "Fotóny červeného a blízkeho infračerveného svetla sa absorbujú v bunkových štruktúrach, kde môžu ovplyvňovať aktivitu cytochrómu c oxidázy, mitochondrií a tvorbu bunkovej energie ATP."],
      ["Červené svetlo 660 nm", "Červené svetlo s vlnovou dĺžkou približne 660 nm sa využíva najmä pri starostlivosti o pokožku, povrchové tkanivá a podporu prirodzených hojivých procesov a tvorby kolagénu."],
      ["Blízke infračervené svetlo 810–850 nm", "Blízke infračervené svetlo približne 810–850 nm preniká hlbšie do tkanív, preto sa využíva pri práci so svalmi, kĺbmi a hlbšími štruktúrami. Presné parametre nastavujeme podľa použitého zariadenia a potrieb klienta."],
      ["Podpora vitality a longevity", "Fotobiomodulácia môže podporovať mitochondriálne a antioxidačné mechanizmy, reguláciu oxidačného stresu a prirodzené procesy bunkovej obnovy. Konkrétny protokol vždy nastavujeme individuálne."],
    ],
    faq: [
      ["Je terapia bolestivá?", "Aplikácia je neinvazívna. Klient môže vnímať mierne teplo; intenzita sa nastaví tak, aby bol priebeh bezpečný a komfortný."],
      ["Prečo sa používajú rôzne vlnové dĺžky?", "Rôzne vlnové dĺžky majú odlišnú penetráciu tkanivami, preto sa vyberajú podľa oblasti a cieľa."],
      ["Potrebujem ochranné okuliare?", "Pri práci s intenzívnym svetelným zdrojom sa používa ochrana očí podľa typu zariadenia a protokolu."],
    ],
  },
  {
    slug: "chiromanualne-terapie",
    short: "Chironeurogénna terapia",
    title: "Chironeurogénna manuálna regeneračná terapia",
    eyebrow: "Pohyb, nervový systém, súvislosti",
    intro:
      "Je naša autorská metóda. Precízne spája špecializované manuálne techniky s hlbokým poznaním vzájomného prepojenia nervového a pohybového systému.",
    image: "/assets/service-manual-concept.jpg",
    duration: "90 minút pri nadväzujúcom stretnutí",
    price: "od 155 €",
    process: [
      "Rozhovor a funkčné zhodnotenie chrbtice, kĺbov, svalov, fascií a pohybových vzorcov.",
      "Výber šetrných manuálnych techník podľa cieľa, veku a tolerancie klienta.",
      "Cielená práca s napätím, pohyblivosťou a funkčnými súvislosťami nervového systému.",
      "Odporúčanie pohybového režimu a ďalších krokov vrátane vhodných technológií.",
    ],
    benefits: ["uvoľnenie svalového a fasciálneho napätia", "podpora pohyblivosti", "podpora funkcie chrbtice a kĺbov", "podpora nervového systému", "podpora lymfatického systému", "cielená práca s bolestivými bodmi"],
    audience: "Pre klientov s bolesťami chrbta, krku, kĺbov alebo svalov, funkčnými obmedzeniami, preťažením či potrebou cielenej regenerácie.",
    suitableFor: ["bolesti chrbta, krku, kĺbov a svalov", "obmedzená mobilita a stuhnutosť", "svalové a fasciálne napätie", "športové preťaženie", "opuchy po odbornom posúdení", "prevencia a aktívny život"],
    modalities: [],
    details: [],
    faq: [
      ["Je ošetrenie vždy spojené s manipuláciou?", "Nie. Použitá technika závisí od vyšetrenia, veku, stavu a súhlasu klienta. Často pracujeme jemne a bez rýchlych manipulačných pohybov."],
      ["Je služba vhodná aj pre deti?", "Áno, po individuálnom posúdení a s technikami primeranými veku. Dieťa prichádza so zákonným zástupcom."],
      ["Môžu sa jednotlivé techniky kombinovať?", "Áno. Kombinácia však vzniká až po vyšetrení a s ohľadom na reakciu tkanív a celkový plán."],
      ["Ako sa pripraviť?", "Odporúčame pohodlné oblečenie a informácie o diagnózach, operáciách, úrazoch, liekoch a aktuálnych obmedzeniach."],
    ],
  },
  {
    slug: "fyzioterapeuticke-poradenstvo",
    short: "Fyzio-regeneračné poradenstvo",
    title: "Fyzio-regeneračné poradenstvo",
    eyebrow: "Pokračujte v starostlivosti aj doma",
    intro:
      "Po terapii vás naučíme jednoduché a bezpečné cviky, ktoré môžete samostatne vykonávať doma. Individuálny plán pomáha nadviazať na terapiu, podporiť pohybové návyky a udržať dosiahnutý pokrok.",
    image: "/assets/service-physio-home-exercise.jpg",
    duration: "podľa vstupného zhodnotenia a rozsahu nácviku",
    price: "individuálne",
    process: [
      "Zhodnotíme váš aktuálny pohyb, možnosti, obmedzenia a reakciu na absolvované terapie.",
      "Vyberieme malý počet zrozumiteľných cvikov podľa vášho cieľa a aktuálneho stavu.",
      "Každý cvik vám prakticky ukážeme a pod dohľadom si nacvičíte správnu techniku, dýchanie aj tempo.",
      "Dostanete odporúčanie, ako často a v akom rozsahu cvičiť doma a ktoré signály tela sledovať.",
      "Pri kontrole vyhodnotíme pokrok, upravíme náročnosť a podľa potreby plán doplníme.",
    ],
    benefits: ["nadviazanie na absolvované terapie", "podpora správnych pohybových návykov", "väčšia istota pri domácom cvičení", "podpora mobility a stability", "postupné budovanie samostatnosti", "dlhodobá starostlivosť o pohyb"],
    audience: "Pre dospelých aj deti po individuálnom posúdení, ktorí chcú na terapiu bezpečne nadviazať domácim cvičením a aktívne sa podieľať na svojom pohybovom pláne.",
    suitableFor: ["pokračovanie po manuálnej alebo regeneračnej terapii", "stuhnutosť a obmedzená pohyblivosť", "potreba zlepšiť stabilitu a koordináciu", "návrat k bežnému pohybu po záťaži", "prevencia opakovaného preťaženia", "budovanie pravidelného domáceho režimu"],
    modalities: ["individuálny pohybový plán", "nácvik správnej techniky", "mobilizačné cvičenia", "stabilizačné cvičenia", "dychové a relaxačné prvky", "odporúčaná frekvencia a rozsah", "kontrola a úprava plánu"],
    details: [
      ["Cvičenie nadväzujúce na terapiu", "Domáci plán vychádza z priebehu terapie, funkčného zhodnotenia a cieľov klienta. Nejde o všeobecnú zostavu rovnakú pre každého."],
      ["Jednoduchý plán, ktorý sa dá dodržať", "Uprednostňujeme menší počet dobre zvládnutých cvikov. Klient presne vie, ako cvik vykonať, koľko opakovaní zvoliť a ako často ho zaradiť."],
      ["Správna technika a bezpečnosť", "Cviky si najprv nacvičíte pod dohľadom. Sledujeme postavenie tela, rozsah pohybu, dýchanie a reakciu organizmu, aby ste ich doma vykonávali s istotou."],
      ["Samostatnosť medzi návštevami", "Pravidelná primeraná aktivita pomáha klientovi aktívne pokračovať v starostlivosti aj medzi stretnutiami a podporuje dlhodobejšie pohybové návyky."],
      ["Kontrola a postupné napredovanie", "Pri ďalšej návšteve vyhodnotíme, čo sa darí a čo treba upraviť. Náročnosť zvyšujeme až vtedy, keď je technika bezpečná a telo reaguje primerane."],
      ["Kedy cvičenie prerušiť", "Cvičenie sa nepraktizuje cez výraznú alebo novú bolesť. Pri zhoršení stavu, závratoch, dýchavičnosti, slabosti alebo inom neobvyklom príznaku treba cvičenie prerušiť a poradiť sa s odborníkom."],
    ],
    faq: [
      ["Dostanem rovnaké cviky ako ostatní klienti?", "Nie. Výber cvikov, rozsah, počet opakovaní a frekvencia sa prispôsobujú vášmu aktuálnemu stavu, cieľu a reakcii na terapiu."],
      ["Koľko času mám doma cvičiť?", "Plán nastavíme tak, aby bol realistický a dlhodobo udržateľný. Presný čas a frekvenciu určí odborník po zhodnotení."],
      ["Potrebujem na cvičenie pomôcky?", "Mnohé cviky možno vykonávať bez pomôcok. Ak je vhodná podložka, elastický pás alebo iná jednoduchá pomôcka, vysvetlíme jej bezpečné použitie."],
      ["Čo ak pri cvičení cítim bolesť?", "Mierne svalové úsilie môže byť prirodzené, ostrá, nová alebo zhoršujúca sa bolesť však nie. Cvik prerušte a kontaktujte nás, aby sme plán upravili."],
      ["Ako zistím, či cviky robím správne?", "Techniku si nacvičíte počas osobného stretnutia. Pri kontrolnej návšteve ju opäť preveríme a podľa potreby opravíme alebo cvik zjednodušíme."],
    ],
  },
] as const;

export const programs = [
  { name: "RESET", price: "305 €", note: "Prvý krok smerom k regenerácii", items: ["2 individuálne stretnutia", "individuálny plán starostlivosti", "možnosť HBOT podľa plánu"] },
  { name: "RESTORE", price: "455 €", note: "Návrat k tomu, čo máte radi", items: ["3 individuálne stretnutia", "individuálny plán starostlivosti", "možnosť HBOT podľa plánu"] },
  { name: "REGENERATE", price: "755 €", note: "Obnova sily a vitality", items: ["5 individuálnych stretnutí", "individuálny plán starostlivosti", "HBOT podľa individuálneho plánu"] },
  { name: "LONGEVITY", price: "1 495 €", note: "Objavujeme čas", items: ["10 individuálnych stretnutí", "komplexný dlhodobý plán", "priebežné hodnotenie a optimalizácia"] },
] as const;

export const faqs = [
  ["Ako prebieha prvá návšteva?", "Začíname rozhovorom, zhodnotením potrieb a cieľov. Následne navrhneme individuálny plán a vysvetlíme odporúčaný postup."],
  ["Je potrebné objednať sa vopred?", "Áno. REVIQA funguje na objednávku, aby sme každému klientovi zabezpečili dostatok času, súkromie a pokojný priebeh návštevy."],
  ["Je centrum vhodné aj pre deti?", "Áno, centrum pracuje aj s deťmi. Vhodnosť konkrétneho postupu sa vždy posudzuje individuálne a návšteva dieťaťa prebieha so zákonným zástupcom."],
  ["Ako dlho trvá návšteva?", "Personalizovaný regeneračný protokol REVIQA Method™ trvá do 90 minút. HBOT trvá približne 60 minút. Dĺžka ďalšej starostlivosti sa prispôsobuje individuálnemu plánu."],
  ["Môžem kombinovať viaceré terapie?", "Áno, ak je to vhodné. Kombinácie a poradie terapií navrhujeme podľa individuálneho plánu, nie podľa univerzálneho balíka."],
  ["Ako zistím, či je terapia pre mňa vhodná?", "Pred začiatkom preberieme váš zdravotný stav, liečbu a možné obmedzenia. O vhodnosti konkrétneho postupu rozhoduje odborné posúdenie."],
  ["Kde môžem zaparkovať?", "Parkovanie je dostupné priamo v objekte centra na adrese Hitschova 5022/2 v Poprade."],
  ["Dá sa objednať aj mimo otváracích hodín?", "Áno. Mimo bežných hodín a počas víkendu je možné dohodnúť termín podľa potreby a dostupnosti."],
] as const;

export const asset = (path: string) => `${process.env.NEXT_PUBLIC_BASE_PATH ?? ""}${path}`;
