export const contact = {
  phoneDisplay: "+421 917 072 074",
  phone: "+421917072074",
  email: "info@reviqa.sk",
  address: "Hitschova 5022/2, 058 01 Poprad – Spišská Sobota, Slovensko",
  whatsapp:
    "https://wa.me/421917072074?text=Dobr%C3%BD%20de%C5%88%2C%20m%C3%A1m%20z%C3%A1ujem%20o%20vstupn%C3%BA%20konzult%C3%A1ciu%20v%20REVIQA.",
};

export const services = [
  {
    slug: "vstupna-diagnostika",
    short: "Diagnostika",
    title: "Vstupná diagnostika a individuálna starostlivosť",
    eyebrow: "Najprv porozumenie",
    intro:
      "Komplexný proces, ktorý nám pomáha porozumieť vášmu telu a pripraviť individuálny plán starostlivosti podľa vašich potrieb, cieľov a aktuálneho stavu.",
    image: "/assets/service-diagnostics-concept.jpg",
    duration: "120 minút pri úvodnom vyšetrení",
    price: "od 165 €",
    process: [
      "Rozhovor – spoločne preberieme anamnézu, životný štýl, faktory ovplyvňujúce váš stav a vaše ciele.",
      "Vyšetrenie – komplexne zhodnotíme pohybový systém, funkčné vzorce a možné súvislosti.",
      "Analýza – získané informácie vyhodnotíme a hľadáme možné príčiny ťažkostí.",
      "Individuálny plán – navrhneme postup starostlivosti prispôsobený vašim potrebám.",
      "Prvé regeneračné stretnutie – začíname prvým individuálne zvoleným krokom na ceste k regenerácii.",
    ],
    benefits: ["hľadanie súvislostí", "individuálny prístup", "plán na mieru", "dlhodobá starostlivosť"],
    audience: "Pre dospelých aj deti, ktorí chcú lepšie porozumieť svojmu stavu a začať systematickú individuálnu starostlivosť.",
    suitableFor: ["pohybové ťažkosti", "chronická únava a vyčerpanie", "nedostatočná regenerácia", "stres a nepokoj", "znížená vitalita", "prevencia a longevity"],
    modalities: ["anamnestický rozhovor", "funkčné vyšetrenie", "analýza súvislostí", "návrh poradia terapií", "priebežné hodnotenie progresu"],
    details: [
      ["Prečo REVIQA", "Nehľadáme iba miesto, ktoré bolí. Snažíme sa porozumieť širším súvislostiam pohybu, nervového systému, životného štýlu a regenerácie."],
      ["Podpora prirodzenej regenerácie", "Cieľom je vytvoriť podmienky, v ktorých môže telo lepšie pracovať s vlastnými adaptačnými a regeneračnými procesmi."],
      ["Dlhodobá vitalita", "Zameriavame sa na kvalitu života, pohyb, funkčnosť a dlhodobú udržateľnosť navrhnutého plánu."],
    ],
    faq: [
      ["Čo si mám priniesť?", "Zoznam liekov, dostupnú zdravotnú dokumentáciu a informácie o predchádzajúcich vyšetreniach alebo terapiách."],
      ["Je prvá návšteva vhodná aj pre dieťa?", "Áno. Dieťa prichádza so zákonným zástupcom a rozsah vyšetrenia sa prispôsobí veku a situácii."],
      ["Dostanem hneď plán?", "Po rozhovore a zhodnotení vám vysvetlíme prvý návrh postupu. Plán sa môže ďalej upravovať podľa reakcie a výsledkov."],
    ],
  },
  {
    slug: "hyperbaricka-oxygenoterapia",
    short: "HBOT",
    title: "Hyperbarická oxygenoterapia (HBOT)",
    eyebrow: "Podpora okysličenia",
    intro:
      "Vedecky používaný postup, pri ktorom klient dýcha kyslík v prostredí so zvýšeným tlakom. Cieľom je zvýšiť dostupnosť kyslíka pre tkanivá a podporiť regeneračný plán.",
    image: "/assets/service-hbot-concept.jpg",
    duration: "približne 60 minút",
    price: "od 50 €",
    process: [
      "Pred terapiou posúdime zdravotný stav, možné kontraindikácie a vhodnosť HBOT.",
      "Počas približne 60-minútového pobytu sa tlak v komore zvyšuje a následne kontrolovane znižuje.",
      "Klient pokojne odpočíva a komunikuje s obsluhou; protokol sa nastavuje individuálne.",
      "Po terapii sledujeme toleranciu a odporúčame ďalšiu frekvenciu podľa plánu.",
    ],
    benefits: ["zvýšená dostupnosť kyslíka", "podpora obnovy tkanív", "podpora hojivých procesov", "podpora vitality", "podpora mozgu a koncentrácie", "súčasť regenerácie po záťaži"],
    audience: "Pre klientov, pri ktorých vstupné odborné posúdenie potvrdí vhodnosť hyperbarickej oxygenoterapie.",
    suitableFor: ["chronická únava", "rekonvalescencia po úrazoch a výkonoch", "športovci a zvýšená fyzická záťaž", "kožné a hojivé ťažkosti", "znížená vitalita", "ďalšie stavy po odbornom odporúčaní"],
    modalities: ["individuálny HBOT protokol", "jedna terapia", "séria 5 terapií", "séria 10 terapií", "kombinácia s ďalšou starostlivosťou"],
    details: [
      ["Zvýšenie okysličenia", "V dodaných podkladoch sa uvádza zvýšená dostupnosť kyslíka v krvi a tkanivách. Konkrétny účinok závisí od tlaku, dĺžky, protokolu a zdravotného stavu."],
      ["Obnova buniek a hojenie", "HBOT sa v regeneračných plánoch využíva na podporu prirodzených hojivých procesov, obnovy tkanív a zotavenia po vybraných typoch záťaže."],
      ["Zápal, bolesť a vitalita", "Podklady uvádzajú možné využitie pri podpore zvládania zápalovej záťaže, bolestivých stavov, imunity, energie a vitality. Tieto tvrdenia podliehajú odbornému schváleniu."],
      ["Mozog a nervový systém", "Medzi uvádzané oblasti patrí podpora kognície, sústredenia a neuroprotektívnych mechanizmov. HBOT nenahrádza neurologické vyšetrenie ani liečbu."],
    ],
    faq: [
      ["Čo budem počas terapie cítiť?", "Pri zmene tlaku môžete cítiť tlak v ušiach podobný letu lietadlom. Obsluha vysvetlí techniky vyrovnávania tlaku."],
      ["Koľko terapií potrebujem?", "Počet závisí od cieľa, zdravotného stavu a reakcie. V cenníku sú jedna terapia a balíky 5 alebo 10 terapií."],
      ["Je HBOT vhodná pre každého?", "Nie. Pred terapiou je potrebné individuálne posúdenie vrátane pľúcnych, ušných a ďalších zdravotných rizík."],
    ],
  },
  {
    slug: "molekularny-vodik",
    short: "H₂ terapia",
    title: "Molekulárna vodíková terapia",
    eyebrow: "Regenerácia na bunkovej úrovni",
    intro:
      "Vodík je najmenšia molekula. V REVIQA ho zaraďujeme do personalizovaných plánov formou inhalácie alebo vodíkovej vody podľa individuálneho cieľa.",
    image: "/assets/service-hydrogen-concept.jpg",
    duration: "podľa individuálneho protokolu",
    price: "na základe plánu",
    process: [
      "Preberieme cieľ, zdravotný stav a miesto vodíkovej terapie v celom pláne.",
      "Vyberieme inhaláciu molekulárneho vodíka, pitie vodíkovej vody alebo ich vhodnú kombináciu.",
      "Nastavíme frekvenciu a dĺžku podľa individuálneho protokolu.",
      "Priebežne sledujeme toleranciu a upravujeme plán podľa potrieb klienta.",
    ],
    benefits: ["antioxidačná podpora", "podpora bunkovej rovnováhy", "podpora energie a vitality", "podpora mozgu a nervového systému", "podpora regenerácie", "začlenenie do longevity plánu"],
    audience: "Pre klientov, ktorí chcú podporiť regeneráciu, vitalitu a ochranu buniek v rámci individuálne posúdeného programu.",
    suitableFor: ["chronická únava", "športová a pracovná záťaž", "regenerácia po výkone", "zápalová záťaž", "podpora imunity", "anti-aging a longevity"],
    modalities: ["inhalácia molekulárneho vodíka", "pitie vodíkovej vody", "individuálny protokol", "kombinácia s HBOT", "dlhodobý regeneračný režim"],
    details: [
      ["Selektívna antioxidačná podpora", "Podklady opisujú molekulárny vodík ako selektívny antioxidant a spájajú ho s ochranou buniek pred oxidačným stresom. Formulácia čaká na odborné potvrdenie."],
      ["Prenikanie na bunkovú úroveň", "Vzhľadom na malú veľkosť molekuly sa v podkladoch uvádza schopnosť prenikať cez biologické membrány. Klinický význam závisí od spôsobu podania a individuálneho stavu."],
      ["Energia, vitalita a nervový systém", "Materiály spájajú H₂ s podporou mitochondrií, bunkovej energie, koncentrácie, spánku a celkovej mentálnej výkonnosti."],
      ["Regenerácia a longevity", "Vodík zaraďujeme ako doplnkový nástroj do širšieho plánu, nie ako náhradu diagnostiky alebo liečby ochorení."],
    ],
    faq: [
      ["Aký je rozdiel medzi inhaláciou a vodíkovou vodou?", "Inhalácia privádza vodík cez dýchacie cesty, vodíková voda cez tráviaci trakt. Výber závisí od cieľa a protokolu."],
      ["Môžem terapiu kombinovať s HBOT?", "Kombinácia je možná iba vtedy, keď ju odporučí individuálny plán a nie sú prítomné kontraindikácie."],
      ["Je vodík liekom?", "Na stránke ho prezentujeme ako doplnkový regeneračný postup. Nenahrádza lekársku diagnostiku, predpísanú liečbu ani lieky."],
    ],
  },
  {
    slug: "fotobiomodulacia",
    short: "Svetelná terapia",
    title: "Fotobiomodulácia",
    eyebrow: "Veda svetla. Energia života.",
    intro:
      "Fotobiomodulácia využíva vybrané vlnové dĺžky červeného a blízkeho infračerveného svetla na podporu prirodzených bunkových a regeneračných procesov.",
    image: "/assets/service-pbm-concept.jpg",
    duration: "podľa zvolenej oblasti a protokolu",
    price: "na základe plánu",
    process: [
      "Určíme cieľovú oblasť, cieľ terapie a vylúčime možné kontraindikácie.",
      "Nastavíme vlnovú dĺžku, vzdialenosť, intenzitu a čas expozície.",
      "Počas neinvazívnej aplikácie klient používa ochranu očí a pokojne odpočíva.",
      "Pri sérii stretnutí sledujeme reakciu a podľa potreby protokol upravujeme.",
    ],
    benefits: ["podpora bunkovej energie ATP", "podpora regulácie zápalovej záťaže", "podpora hojenia a obnovy tkanív", "podpora svalov a kĺbov", "podpora mozgu a nervov", "podpora vitality a longevity"],
    audience: "Pre dospelých aj deti, ak je svetelná terapia po odbornom posúdení vhodná a je možné bezpečne nastaviť protokol.",
    suitableFor: ["regenerácia kože a povrchových tkanív", "svaly, šľachy a kĺby", "zotavenie po záťaži", "podpora hojenia", "podpora výkonu", "longevity programy"],
    modalities: ["červené svetlo približne 660 nm", "blízke infračervené svetlo približne 810–850 nm", "lokálna aplikácia", "celotelový panel", "séria podľa individuálneho plánu"],
    details: [
      ["Ako svetlo pôsobí", "Fotóny červeného a blízkeho infračerveného svetla sa absorbujú v bunkových štruktúrach. Podklady opisujú väzbu na cytochróm c oxidázu, mitochondrie a tvorbu ATP."],
      ["Červené svetlo 660 nm", "V podkladoch je spojené najmä s pokožkou, hojením rán, tvorbou kolagénu a regeneráciou povrchovejších tkanív."],
      ["Blízke infračervené svetlo 810–850 nm", "Materiály ho spájajú s hlbšou penetráciou a využitím pri svaloch, kĺboch a hlbších tkanivách. Presné parametre závisia od zariadenia."],
      ["Uvádzané mechanizmy longevity", "Dodaný materiál uvádza podporu mitochondriálnej biogenézy, antioxidačných mechanizmov, ochrany telomér, regulácie oxidačného stresu a autofágie. Text čaká na odborné schválenie."],
    ],
    faq: [
      ["Je terapia bolestivá?", "Aplikácia je neinvazívna. Klient môže vnímať mierne teplo; intenzita sa nastaví tak, aby bol priebeh bezpečný a komfortný."],
      ["Prečo sa používajú rôzne vlnové dĺžky?", "Rôzne vlnové dĺžky majú odlišnú penetráciu tkanivami, preto sa vyberajú podľa oblasti a cieľa."],
      ["Potrebujem ochranné okuliare?", "Pri práci s intenzívnym svetelným zdrojom sa používa ochrana očí podľa typu zariadenia a protokolu."],
    ],
  },
  {
    slug: "chiromanualne-terapie",
    short: "Chiromanuálne terapie",
    title: "Chiromanuálne a regeneračné terapie",
    eyebrow: "Pohyb, nervový systém, súvislosti",
    intro:
      "Komplexný prístup k obnove neuromuskuloskeletálneho systému pomocou šetrných manuálnych techník, funkčného vyšetrenia a individuálneho plánu.",
    image: "/assets/service-manual-concept.jpg",
    duration: "90 minút pri nadväzujúcom stretnutí",
    price: "od 155 €",
    process: [
      "Rozhovor a funkčné zhodnotenie chrbtice, kĺbov, svalov, fascií a pohybových vzorcov.",
      "Výber šetrných manuálnych techník podľa cieľa, veku a tolerancie klienta.",
      "Cielená práca s napätím, pohyblivosťou a funkčnými súvislosťami nervového systému.",
      "Odporúčanie pohybového režimu a ďalších krokov vrátane vhodných technológií.",
    ],
    benefits: ["uvoľnenie napätia", "podpora pohyblivosti", "podpora funkcie chrbtice a kĺbov", "podpora nervového systému", "zlepšenie komfortu pohybu", "dlhodobá prevencia"],
    audience: "Pre klientov s bolesťami chrbta, krku, kĺbov alebo svalov, funkčnými obmedzeniami, preťažením či potrebou cielenej regenerácie.",
    suitableFor: ["bolesti chrbta, krku, kĺbov a svalov", "obmedzená mobilita a stuhnutosť", "svalové a fasciálne napätie", "športové preťaženie", "stres a nedostatočné uvoľnenie", "prevencia a aktívny život"],
    modalities: ["chiropraxia a kĺbová mobilizácia", "mäkké techniky", "Dornova metóda", "fasciálna terapia", "neuromuskulárne techniky", "funkčný pohybový plán"],
    details: [
      ["Chrbtica a kĺby", "Cieľom je podpora pohyblivosti, funkcie kĺbov a stavcov a zníženie mechanického preťaženia nervových a mäkkých štruktúr."],
      ["Nervový systém", "Manuálnu starostlivosť prepájame s prácou na napätí, dýchaní a pohybových vzorcoch, ktoré môžu ovplyvniť celkový komfort a regeneráciu."],
      ["Svaly a fascie", "Mäkké a fasciálne techniky sú zamerané na uvoľnenie napätia, zlepšenie elasticity tkanív a podporu prirodzenejšieho pohybu."],
      ["Celostný kontext", "Podklady zdôrazňujú súvislosti medzi postavením pohybového aparátu, nervovou komunikáciou, prekrvením a funkciou tela. Nejde o sľub liečby orgánových ochorení."],
    ],
    faq: [
      ["Je ošetrenie vždy spojené s manipuláciou?", "Nie. Použitá technika závisí od vyšetrenia, veku, stavu a súhlasu klienta. Často pracujeme jemne a bez rýchlych manipulačných pohybov."],
      ["Je služba vhodná aj pre deti?", "Áno, po individuálnom posúdení a s technikami primeranými veku. Dieťa prichádza so zákonným zástupcom."],
      ["Ako sa pripraviť?", "Odporúčame pohodlné oblečenie a informácie o diagnózach, operáciách, úrazoch, liekoch a aktuálnych obmedzeniach."],
    ],
  },
  {
    slug: "doplnkove-terapie",
    short: "Doplnkové terapie",
    title: "Doplnkové regeneračné terapie",
    eyebrow: "Starostlivosť zostavená na mieru",
    intro:
      "Podľa potrieb kombinujeme mäkké a fasciálne techniky, Dornovu metódu, lymfodrenáž, bankovanie, kineziotaping a trigger-point terapiu.",
    image: "/assets/service-complementary-concept.jpg",
    duration: "podľa zvoleného postupu",
    price: "individuálne",
    process: [
      "Určíme cieľ stretnutia a vyberieme jednu alebo viac primeraných techník.",
      "Vysvetlíme očakávaný priebeh, možné reakcie kože alebo tkanív a získame súhlas klienta.",
      "Techniku aplikujeme s ohľadom na toleranciu, vek a aktuálny stav.",
      "Výsledok zhodnotíme a podľa potreby ju zaradíme do širšieho regeneračného programu.",
    ],
    benefits: ["uvoľnenie svalového a fasciálneho napätia", "podpora mobility", "podpora lymfatického systému", "podpora stabilizácie svalov a kĺbov", "cielená práca s bolestivými bodmi", "personalizovaná kombinácia"],
    audience: "Pre klientov, ktorým funkčné vyšetrenie a individuálny plán odporučia konkrétnu doplnkovú techniku.",
    suitableFor: ["svalové napätie a spazmy", "stuhnutosť a obmedzená pohyblivosť", "opuchy po odbornom posúdení", "športové preťaženie", "potreba stabilizácie", "lokálne bolestivé body"],
    modalities: ["mäkké techniky", "Dornova metóda", "lymfodrenáž", "fasciálna terapia", "bankovanie", "kineziotaping", "trigger-point terapia"],
    details: [
      ["Mäkké a fasciálne techniky", "Zameriavajú sa na svalové napätie, fascie a hlbšie tkanivá s cieľom podporiť elasticitu, pohyblivosť a komfort."],
      ["Dornova metóda", "Jemný manuálny prístup pracujúci s pohybom a postavením kĺbov a chrbtice. Používa sa len po vyhodnotení vhodnosti."],
      ["Lymfodrenáž", "Jemná technika zameraná na podporu lymfatického toku a prácu s vybranými typmi opuchov. Vyžaduje dôsledné posúdenie kontraindikácií."],
      ["Bankovanie", "Práca s podtlakom môže podporiť lokálne prekrvenie a uvoľnenie napätia. Dočasné kožné stopy sú možnou reakciou."],
      ["Kineziotaping", "Elastická páska sa používa ako doplnok na podporu pohybu, vnímania a vybraných svalových alebo kĺbových funkcií."],
      ["Trigger-point terapia", "Cielená práca s citlivými bodmi vo svaloch a fasciách, ktoré môžu súvisieť s lokálnou alebo prenesenou bolesťou."],
    ],
    faq: [
      ["Môžu sa techniky kombinovať?", "Áno. Kombinácia však vzniká až po vyšetrení a s ohľadom na reakciu tkanív a celkový plán."],
      ["Zostávajú po bankovaní stopy?", "Môžu vzniknúť dočasné farebné stopy. Pred aplikáciou vysvetlíme očakávanú reakciu a kontraindikácie."],
      ["Ako dlho zostáva kineziotape na koži?", "Dĺžku určí terapeut podľa cieľa a reakcie kože. Pri podráždení sa páska odstráni."],
    ],
  },
] as const;

export const programs = [
  { name: "RESET", price: "305 €", note: "Prvý krok smerom k regenerácii", items: ["2 individuálne stretnutia", "individuálny plán starostlivosti", "možnosť HBOT podľa plánu"] },
  { name: "RESTORE", price: "455 €", note: "Návrat k tomu, čo máte radi", items: ["3 individuálne stretnutia", "individuálny plán starostlivosti", "možnosť HBOT podľa plánu"] },
  { name: "REGENERATE", price: "755 €", note: "Obnova sily a vitality", items: ["5 individuálnych stretnutí", "individuálny plán starostlivosti", "HBOT podľa individuálneho plánu"] },
  { name: "LONGEVITY", price: "1 495 €", note: "Objavujeme čas", items: ["10 individuálnych stretnutí", "komplexný dlhodobý plán", "priebežné hodnotenie a optimalizácia"] },
] as const;

export const faqs = [
  ["Ako prebieha prvá návšteva?", "Začíname rozhovorom, zhodnotením potrieb a cieľov. Následne navrhneme individuálny plán a vysvetlíme odporúčaný postup."],
  ["Je potrebné objednať sa vopred?", "Áno. REVIQA funguje na objednávku, aby sme každému klientovi zabezpečili dostatok času, súkromie a pokojný priebeh návštevy."],
  ["Je centrum vhodné aj pre deti?", "Áno, centrum pracuje aj s deťmi. Vhodnosť konkrétneho postupu sa vždy posudzuje individuálne a návšteva dieťaťa prebieha so zákonným zástupcom."],
  ["Ako dlho trvá návšteva?", "Úvodné komplexné vyšetrenie trvá približne 120 minút. Nadväzujúce stretnutie približne 90 minút a HBOT približne 60 minút."],
  ["Môžem kombinovať viaceré terapie?", "Áno, ak je to vhodné. Kombinácie a poradie terapií navrhujeme podľa individuálneho plánu, nie podľa univerzálneho balíka."],
  ["Ako zistím, či je terapia pre mňa vhodná?", "Pred začiatkom preberieme váš zdravotný stav, liečbu a možné obmedzenia. O vhodnosti konkrétneho postupu rozhoduje odborné posúdenie."],
  ["Kde môžem zaparkovať?", "Parkovanie je dostupné priamo v objekte centra na adrese Hitschova 5022/2 v Poprade."],
  ["Dá sa objednať aj mimo otváracích hodín?", "Áno. Mimo bežných hodín a počas víkendu je možné dohodnúť termín podľa potreby a dostupnosti."],
] as const;

export const asset = (path: string) => `${process.env.NEXT_PUBLIC_BASE_PATH ?? ""}${path}`;
