import { PageHero, SectionHeading } from "@/components/Sections";
import { contact } from "@/lib/content";
import { createPageMetadata } from "@/lib/seo";

export const metadata = createPageMetadata({ title: "Kontakt a objednanie konzultácie", description: "Kontaktujte REVIQA Biomedica: Hitschova 5022/2, 058 01 Poprad. Objednanie vstupnej konzultácie telefonicky alebo cez WhatsApp.", path: "/kontakt" });

export default function ContactPage() {
  return <><PageHero eyebrow="Kontakt" title="Vaša cesta začína rozhovorom" text="Objednajte si vstupnú konzultáciu telefonicky alebo cez WhatsApp. Kontaktný formulár nepoužívame – komunikujete priamo s nami." /><section className="section shell contact-layout"><div><SectionHeading eyebrow="REVIQA Poprad" title="Kontakt a otváracie hodiny" /><div className="contact-cards"><a href={`tel:${contact.phone}`}><small>Telefón</small><b>{contact.phoneDisplay}</b></a><a href={`mailto:${contact.email}`}><small>E-mail</small><b>{contact.email}</b></a><div><small>Adresa</small><b>{contact.address}</b></div><div><small>Otváracie hodiny</small><b>Po–Pi 9:00–12:00<br />13:00–15:00</b><p>Víkend a iný čas podľa potreby, na objednávku.</p></div></div><div className="contact-actions"><a className="gold-button" href={contact.whatsapp} target="_blank" rel="noreferrer">Napísať cez WhatsApp</a><a className="ghost-button" href={`tel:${contact.phone}`}>Zavolať</a></div><p className="access-note">✓ Parkovanie priamo v objekte &nbsp; ✓ Bezbariérový vstup</p></div><div className="map-embed"><iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d199735.6963376034!2d20.152553270098007!3d49.01102797600171!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x473e3b8f55e5821b%3A0xa48b688bd1373dd1!2sReviqa%20Biomedica!5e1!3m2!1scs!2ssk!4v1784717514004!5m2!1scs!2ssk" title="Google mapa – REVIQA Biomedica, Hitschova 5022/2, Poprad" loading="lazy" allowFullScreen referrerPolicy="strict-origin-when-cross-origin" /><a href="https://www.google.com/maps/search/?api=1&query=Reviqa%20Biomedica%2C%20Hitschova%205022%2F2%2C%20058%2001%20Poprad%2C%20Slovakia" target="_blank" rel="noreferrer">Otvoriť trasu v Google Maps</a></div></section></>;
}
